version: '3.8'

services:
  jupyterhub:
    build:
      context: ../../src/services/backend/jupyter_hub
      dockerfile: Dockerfile
    container_name: beta-jupyterhub
    ports:
      - "10000:8000"
    volumes:
      - ../../resources/config/jupyterhub:/srv/jupyterhub:rw
      - ../../src/services/backend/jupyter_hub_adapter_microservice/sendCode.py:/home/developer/sendCode.py:rw #MUST BE ro
      - ../../resources/data/jupyterhub:/home/developer:rw
    environment:
      - LLM_VALIDATOR_URL=http://10.100.30.239:9001

  mediator:
    build:
      context: ../../src/services/backend/mediator_jupyter_hub_llm_microservice
      dockerfile: Dockerfile
    container_name: beta-mediator
    ports:
      - "9001:8001"
    environment:
      - PYTHONUNBUFFERED=1
      - FEEDBACK_SERVICE_URL=http://10.100.30.239:10352

    volumes:
      - ../../src/services/backend/mediator_jupyter_hub_llm_microservice:/app:rw

  feedback-service:
    build:
      context: ../../src/services/ml/feedback
      dockerfile: Dockerfile
    container_name: beta-feedback
    ports:
      - "10352:9352"
    env_file:
      - ../../src/services/ml/feedback/.env
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ../../src/services/ml/feedback:/app:ro